services:
  db:
    container_name: todo-db
    image: postgres
    restart: always
    networks:
      - todo-network
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PSWD}
      POSTGRES_DB: ${DB_DBNAME}

networks:
  todo-network:
    name: todo-network
    driver: bridge
